"server":
    "port": 80
    "read_timeout": 15
    "write_timeout": 15
    "idle_timeout": 60
"database":
    "host": "127.0.0.1"
    "port": 5432
    "user": ""
    "password": ""
    "db_name": ""
    "ssl_mode": "require"
    "max_open_conns": 0
    "max_idle_conns": 2
    "conn_max_lifetime": 0
    "migrate_source": ""
"message_broker":
    "host": "127.0.0.1"
    "port": 4222
