version: "3.7"

networks:
    demo-net:

volumes:
    postgres-data:

services:
    client:
        build:
            context: ./client
            dockerfile: ./build/Dockerfile
        networks:
            - demo-net

    service:
        build:
            context: ./service
            dockerfile: ./build/Dockerfile
        deploy:
            replicas: 3
        networks:
            - demo-net
        depends_on:
            - postgres
            - nats
        labels:
            - traefik.enable=true
            - traefik.http.routers.service.rule=Host(`service.lvh.me`)
            - traefik.http.routers.service.entrypoints=web
            - traefik.http.services.service.loadbalancer.server.port=9000
            - traefik.http.services.service.loadbalancer.server.scheme=h2c

    postgres:
        image: postgres:12-alpine
        networks:
            - demo-net
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_DB=postgres

    nats:
        image: nats:2
        networks:
            - demo-net

    traefik:
        image: traefik:2.1
        ports:
            - 80:80
        networks:
            - demo-net
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - TRAEFIK_PROVIDERS_DOCKER=true
            - TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT=false
            - TRAEFIK_ENTRYPOINTS_WEB=true
            - TRAEFIK_ENTRYPOINTS_WEB_ADDRESS=:80
            - TRAEFIK_API_DASHBOARD=true
        labels:
            - traefik.enable=true
            - traefik.http.routers.traefik.rule=Host(`traefik.lvh.me`)
            - traefik.http.routers.traefik.service=api@internal
            - traefik.http.routers.traefik.entrypoints=web
